const { execSync } = require('child_process')
let string = process.argv[2].split('').join(' ').toString()
string = string.replace(': d', '0xff08')
string = string.replace(': r', '0xff0d')
execSync(`DISPLAY=:0 xdotool key ${ string }`)